name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: dev-axnn/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 25f3caebf293b0cf8023815c767928d6
          TIMEZONE: Asia/Seoul
